name: test

on:
  pull_request_review:
    types: [submitted]
    branches: ['main']

jobs:
  test-usage:
    if: ${{ github.event.review.state == 'approved' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.review.commit_id }}

      - name: Notarize and verify PR
        uses: codenotary/notarize-and-verify-pr-action@v1.0.0
        # uses: codenotary/notarize-and-verify-pr-action@main
        with:
          cnil_rest_api_url: ${{ secrets.CNIL_REST_API_URL }}
          cnil_personal_token: ${{ secrets.CNIL_PERSONAL_TOKEN }}
          cnil_grpc_host: ${{ secrets.CNIL_GRPC_HOST }}
          cnil_grpc_port: ${{ secrets.CNIL_GRPC_PORT }}
          cnil_ledger: ${{ secrets.CNIL_LEDGER_ID }}
          required_pr_approvers: dmacvicar,padurean-alt
          current_pr_approver: ${{ github.event.review.user.login }}
